sudo: false

language: elixir

elixir:
- 1.2.3

otp_release:
- 18.2

sudo: false

install:
- mix local.hex --force
- mix deps.get

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database gebetsgruppe_test;' -U postgres

script: mix test
