sudo: false

language: elixir

elixir:
- 1.2.0

otp_release:
- 18.2

sudo: false

install:
- mix local.hex --force
- mix deps.get

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - psql -c 'create database phoenix_guardian_test;' -U postgres
  
script: mix test
